language: cpp
compiler:
  - gcc
  - clang
before_install:
  # Add repo for gcc 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libtool automake 

  # Always install g++
  - sudo apt-get install -qq g++-4.8
  - sudo apt-get install -qq g++-4.8-multilib
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
before_script:
  - mkdir -p $HOME/lib
  - autoreconf -i 
  - ./configure --prefix=$HOME/lib/warped 
script: 
  - make V=1 -j5 && make check && make install && make distcheck -j5